CREATE TABLE employee (
employee_id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
first_name VARCHAR(40) NOT NULL,
last_name VARCHAR(40) NOT NULL,
birth_date DATE NOT NULL,
hire_date DATE NOT NULL,
address VARCHAR(128) NOT NULL,
city VARCHAR(30) NOT NULL,
country VARCHAR(30) NOT NULL
);

-- Relaccion 1 a 1 